# Generated by Django 5.1.6 on 2025-06-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0003_donations'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
