# Generated by Django 5.1.6 on 2025-06-26 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0007_requests_ngo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donations',
            old_name='status',
            new_name='donation_status',
        ),
        migrations.RenameField(
            model_name='requests',
            old_name='status',
            new_name='request_status',
        ),
    ]
