# Generated by Django 5.1.6 on 2025-06-26 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0008_rename_status_donations_donation_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='food',
            new_name='donation_id',
        ),
    ]
