# Generated by Django 5.1.6 on 2025-06-27 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0009_rename_food_requests_donation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='donr_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donate.user'),
        ),
    ]
