# Generated by Django 5.1.6 on 2025-06-27 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0010_requests_donr_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='donr_id',
        ),
    ]
