# Generated by Django 5.1.6 on 2025-06-27 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0011_remove_requests_donr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='login_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donate.login'),
        ),
    ]
