# Generated by Django 5.1.6 on 2025-06-30 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0013_alter_user_login_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='donor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donr', to='donate.login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donate.login'),
        ),
    ]
