# Generated by Django 5.1.6 on 2025-07-11 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0014_requests_donor_id_alter_user_login_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donations',
            old_name='name',
            new_name='food_name',
        ),
    ]
